data-edu/data-science-in-education

README.md, planning/process_questions.Rmd
I added an audience section to our planning questions and did some format clean up. I also added my contact info to `README.md` and edited so the GitHub handles showed when rendered.
=> Edit process

planning/outline.Rmd, planning/outline_brainstorm.Rmd, planning/process_questions.Rmd
Reverts jrosen48/data-science-in-education#5
=> Revert "Revert "Post conference call PR""

11-resources.Rmd
Added resources Rmd file and entered general information and link to the NCRPP file that was recently shared on [Twitter](https://twitter.com/jrosenberg6432/status/969617792378040320).
=> added resources Rmd file

02-how-to-use.Rmd
This is an initial draft of this chapter. I thought back to that last meeting and tried to reflect what we talked about, but please feel free to make changes if I didn't get some of that right.
=> Draft How to Use

README.md
I added the narrative structure from issue #18 to the readme
=> Add narative structure

03-ds-role.Rmd
Here's my take on chapter three. The basic ideas are: 
- There are some similarities among the work of data scientists in education broadly, but lots of variety when you look at the day-to-day work
- Ultimately, exploring these similarities and differences will build the story of what a data scientist in education becomes in the future 
- We can nurture the relationship between data science and education by building it around the unique needs of students, staff, and administrators 
Here are some of the questions to explore for this chapter: 
- I wrote from the point of view of "we." Is that what we want? 
- I used people's examples that they shared with me. I tried my best, but feel free to edit and tell your own story 
- If your story isn't in there, add it! If you do this, consider …
=> Draft of Chapter Three

07-walkthrough-1.Rmd
making some additions to this before next meeting
=> Merging joining additions

10-solutions.Rmd, xx-walkthrough-04.Rmd
All, here is an initial draft of a social network analysis walkthrough.
=> Sna walkthrough

06-walkthrough-1.Rmd
#44 came through my inbox, and although I now realize this is walkthrough 1, the file started with 6. 
I noticed that there were some formatting inconsistencies (when to use`::` even if a package was loaded with `library`, lines longer than 80 characters, some repetitive code, and a few cases where the `tidyverse` has a great built-in function for something done in a step or two) that fit with the idea of this mixing base plus tidyverse. I thought I'd tidy it up.
1. I broke up lines longer than 80 characters. I tried to stick to the tidyverse style guide on this, although my personal style guide differs a bit.
2. I extracted a repeated `mutate` step into a small function of its own.
3. I removed the use of `car::recode`. Although there is `dplyr::recode` it's really designed to work with …
=> 06 - Walkthrough with a bit more tidy verse

08-walkthrough-3.Rmd, 13-learning-more.Rmd
sorry, this was on a branch with the wrong name
=> update learning more

planning/rationale.Rmd
Included the often siloed nature of the data (think SIS, LMS, Gov't data) and the technical awareness of how to access that data (system export or API knowledge)
=> Updated rationale

06-walkthrough-1.Rmd
Here are some proposed changes based on feedback from readers. I didn't get through the whole document, but I tried to make the connections between the narrative and code chunks more explicit so readers can review the code and learn what's happening, even if they don't totally understand the syntax. I got all the way through the section where we find the mean of the survey responses.
=> Add more descriptive text to walkthrough #1

12-solutions.Rmd
Let's not merge this one just yet. I just wanted to do the PR so everyone can give input as I push the draft along. This is super rough but I'm going to keep on pushing commits to this branch until there's a substantial section that feels complete. I'll merge at that point. Feel free to comment and collaborate on this one. Thanks!
=> Add to speed section. Don't merge–more coming! 

12-solutions.Rmd
These are first drafts of the empathy, daily practice, and k-12 teacher sections
=> Add remaining sections

10a-walkthrough-6.Rmd
=> Adding visualizations

r/book-status.R
this is a little script to check word counts, using the {wordcountaddin} package (h/t @ivelasq)
I'd like to also add lines of code, perhaps via the {tidycode} package.
=> add dir for r scripts and add script to count words

10a-walkthrough-6.Rmd, README.md
This set of commits will be for adding narrative to the plots and model
=> Add narrative to vis

10a-walkthrough-6.Rmd
Ok @jrosen48 this should do it. Review away!
=> Add text back in

10a-walkthrough-6.Rmd
Forgot to add this last group of quick edits
=> Make quick edits

10a-walkthrough-6.Rmd
Remaining changes from the last review
=> Add citations

13-students-doing-data-science.Rmd
Opening this as I work on chapter 13. This is presently a *very* rough draft.
=> C 13 on teaching and learning data science

01-intro.Rmd
This PR addresses issue #124 and #79
=> Add description of walkthrough themes

10a-walkthrough-6.Rmd
Misc edits (reads way better now), turned off the dataedu theme so the code runs until we fix it (see #131), and tidied up the headings. Should be bookdown ready. This PR addresses #122
=> Bunch of edits after my read aloud

13-teaching-data-science.Rmd
add k-12 curricula and rename file
=> Update and rename 13-students-doing-data-science.Rmd to 13-teaching-data-science.Rmd

16-learning-more.Rmd
=> Make readability edits

18-conclusion.Rmd
This is a very rough draft (more an outline) of a conclusion, focused on taking on challenges and some strategies for dealing with the frustrations that will inevitably come from it. Related to #162
=> add draft/outline of conclusion

_08-walkthrough-3.Rmd
Major overhaul to chapter 8, most of which was reviewed by Jesse already. Commit 1 of 2, rest happening after I can correctly load our package and test more of the code.
Headings should be right now
=> Chapter 8 Edits

05-foundational-skills.Rmd, 06-wt-multilevel-models-1.Rmd, 07-wt-multilevel-models-2.Rmd
Introduce these functions in chapter 6. I checked in subsequent chapters to make sure there weren't separate introductions.
=> Introduce filter, group_by, and summarize

06-wt-multilevel-models-1.Rmd, 08-wt-gradebooks.Rmd, 10-wt-text-analysis.Rmd, 13-wt-longitudinal-analysis.Rmd
Coordinate introductions for arrange, select, sample_n, and linear models
=> Intro more functions

r/theme_dataedu.R
=> Add prompt = FALSE

10-wt-text-analysis.Rmd, 13-wt-longitudinal-analysis.Rmd
=> Theme text analysis

10-wt-text-analysis.Rmd
@ivelasq Can you have a look at this and see if this is a good implementation of the walkthrough organization you shared? Let's not merge it yet–you've got a big PR pending and I don't want to cause conflicts. Just let me know what you think and I can do the PR again after we merge yours
=> DON'T MERGE: Edit headings based on walktrhough organization doc

10-wt-text-analysis.Rmd
=> Add explanation of API

05-foundational-skills.Rmd
updating chapter 5 to comply with naming in master repo
=> fixing naming mess

_08-walkthrough-3.Rmd, book.bib
Loading data from dataedu pkg and adding more explanation of predictors & rationale for selecting ML model. Also adding a rough outline of additional info to be added based on Jesse's comments + adding new ref to book.bib file
=> Ch 8 interim changes

10-wt-text-analysis.Rmd
Addresses typo in PR #211 by @jonduan
=> Text analysis typo

06-wt-multilevel-models-1.Rmd, 19-references.R
this adds a few paragraphs on atypical joins. I'd welcome a review of it!
I note that while doing this, I started to transition the data input to loading data from the package (in this dataedu package PR: https://github.com/data-edu/dataedu/pull/19).
=> Adding atypical joins

07-wt-ed-ds-pipeline.Rmd, 13-wt-multilevel-models.Rmd
=> Using dataedu package for online science data

07-wt-ed-ds-pipeline.Rmd, 13-wt-multilevel-models.Rmd
This makes the changes @jonduan suggested in #211 to avoid merge conflicts.
=> Address corrections from jonduan

07-wt-ed-ds-pipeline.Rmd, 11-wt-text-analysis.Rmd
Hey @jrosen48 would you mind reviewing and approving these when ready? I got to line 245 but wanted to keep it at a manageable chunk for you to review. If it looks good, go ahead and approve but *don't merge*. I'll keep on suggesting changes on this branch, request review, and will merge at the end for us.
=> 07 code edits

01-introduction.Rmd, 02-how-to-use.Rmd
Editing narrative in Ch1 and Ch2
=> Narrative edits for flow and voice: Ch1 and Ch2

06-foundational-skills_2.Rmd
completed all content to FS2 - still need to incorporate content pulled from FS1.
=> Fs2 first edits

05-foundational-skills_1.Rmd, 08-wt-gradebook.Rmd
edited for content and clarity
=> foundational skills 1 edits

08-wt-gradebook.Rmd
added in a brief conclusion to the walkthrough and made some light edits as I was reading it. will likely need to go back through and re-work the sections that rely on hard-coding file paths, rather than using Projects + `here()`
=> light edits + conclusion

02-how-to-use.Rmd
Making the change we discussed in 1.7.2020 meeting
=> adding language about how to contribute via git or email

09-wt-aggregate-data.Rmd
Hello @ivelasq let me know if you like these changes, but don't merge just yet. I've got a few more lines to review. I'll push any more changes to this branch and will request your review. Then I can merge everything at once.  
A couple more thoughts, though these would be  bigger changes than we should include in this PR. Just things to consider–I don't know at this stage in the game if we want to make changes this big. 
1. We could include the output for the tabulizer import in the package so folks can import and work through the processing section. I found myself wanting to run the cleaning code to see how it all worked but I didn't have the tabulizer output
2. We could also consider changing `merged_df` and `tidy_df` object names to something a little more communicative about what's …
=> 09 code edits

10-wt-longitudinal-analysis.Rmd
Working through a review on the code. I'll keep this open until I get to the end then I'll merge
=> Code edits for longitudinal data walkthrough

05-foundational-skills_1.Rmd, 06-foundational-skills_2.Rmd
I wanted to more clearly differentiate the difference between base R, pre-installed packages, and packages that the user installs. it's still not where I want it (and maybe too much information?) but it's better than where it was.
=> edits to language on base R

11-wt-text-analysis.Rmd
Will merge once I review the rest of the code
=> Code review: text analysis

08-wt-gradebook.Rmd
This involves small edits according to the walkthrough template (see #191). I will highlight a few questions I have momentarily.
=> C8 template edits

18-additional-resources.Rmd
- In section, `Articles related to data science in education`, added reference to our publication on Educational Data Mining _(please consider adding our publication to this list)_
- In section `Programming with R`, added annotations for books, "R for data science", "R cookbook".
- In section `Helpful package vignettes and descriptions of packages` added annotations for packages `dplyr, caret, tidy data`.
=> modified page

12-wt-social-network-analysis.Rmd
I tested lines 87-103 with and without the `has_mention` variable and got the same result so I removed it. 
Before calling `unnest`, there are no NAs in the `all_mentions` column when it's a list column. After calling `unnest`, it looks like R drops any row that didn't have a username in the `all_mentions` column. 
@jrosen48 Let's keep this one open until I review the rest of the code, but wanted you to see it and give me a gut check on what I was seeing.
=> 12 code edits

12-wt-social-network-analysis.Rmd
this is to improve the sociogram (network plot) in the social network analysis chapter
=> begin to improve plots

13-wt-multilevel-models.Rmd
adding headers based on the template for chapter 13. to address #190.
=> Adding headers c13

11-wt-text-analysis.Rmd, 12-wt-social-network-analysis.Rmd
This adds headers per our header template (see template [here](#189)).
While doing this, I saw some content that I think belongs better in chapter 11 (text analysis); data on accessing Twitter data, particularly. @restrellado, I moved this over, but want you to have the last word on this. It involves the addition of some text to the narrative, and a short "Technical Appendix" on different ways to access Twitter data. I think these appendices (maybe they belong at the end of the book, instead of each chapter) may be a way of easing the complexity of some of the content, especially content that isn't core to the topic or the "learning goals" for the chapter.
=> C12 headers

.gitignore, README.md
Plus some .gitignore additions that probably don't matter but I can't figure out how to remove from this commit
=> Documentation Updates

15-data-science-in-your-job.Rmd
Changed `gather()` to `pivot_longer()`, plus other improvements
=> Change gather

05-foundational-skills_1.Rmd
added image link for the R and RStudio icons
=> added icon images

14-wt-machine-learning.Rmd
this adds an explanation of how the c14 dataset is different from that in c7 and c13
=> minor addition

02-how-to-use.Rmd
All of your hyphenated statements are without spacing. Is this a stylistic choice/precedent? It seems odd to me, but could be personal choice.
Nice layout of what this book is, and is not, meant for.
=> Proof 02-how-to-use.Rmd

_book/01-introduction.md
"Learning Data Science in Education" is ambiguous. Simple shift from "Learning..." to "The role of..." helps fix that.
=> Proofing 01-introduction.md

03-data-scientist-in-edu.Rmd
minor change to the title for c3, from:
*What is a Data Scientist in Education*
to:
*Who Data Science in Education?*
Is this okay?
=> Suggested change to c3 title

19-conclusion.Rmd
=> First draft of conclusion chapter 

07-wt-ed-ds-pipeline.Rmd
=> C7 jmr copyedits

08-wt-gradebook.Rmd
=> C8 jmr edits

07-wt-ed-ds-pipeline.Rmd
=> Update narrative from using read_csv to getting data from package

09-wt-aggregate-data.Rmd, 10-wt-longitudinal-analysis.Rmd
@ivelasq quick Q for you - in the context of c9 (aggregate data), do you have thoughts on mentioning equity and the type of data (district-level)?
i.e., changing the title from:
*Introduction to Aggregate Data*
to:
*Introduction to Aggregate Data to Illuminate Educational Inequities Using District-Level Data*
Perhaps the revision is too wordy. Curious what you think, tho, in general, and possibly mentioning either equity or district-level data if this is too wordy!
=> C9 c10 jmr edits

17-learning-more.Rmd
Two citations not rendered. Corrected `@woo` to `@woo18` and `@hill2018` to `@hill2017`, which reflect the keys in the book.bib file
=> fixed citation errors

13-wt-multilevel-models.Rmd, 14-wt-machine-learning.Rmd
this adds overviews for c13 and c14
=> C13 c14 jmr edits

02-how-to-use.Rmd
This resolves #280. Also includes an update to one of our reader quotes.
=> Expand explanation of rating system in chapter 2

05-foundational-skills_1.Rmd
I'm not sure if this should live in Chapter 5 or not, but I've added content that's ready for review! this is based on the "Learning to Learn" post that I wrote regarding the `coalesce()` function, and should provide guidance for readers when they encounter new or unfamiliar content.
=> added section on exploring new and unfamiliar content

index.Rmd
Closes #163 but feel free to add more contributors
=> Additions to acknowledgements section 

06-foundational-skills_2.Rmd, 07-wt-ed-ds-pipeline.Rmd
=> Update URLs in ch 7 + minor edit

book.bib, packages.bib
this is intended to address #387. In addition to regenerating the `packages.bib` file, it sorts the references in both that file and `book.bib` by the authors' name, then the title, then the year.
=> update bib files

16-teaching-data-science.Rmd
Forgot to put this one in a separate branch sorry!
=> Update URLs in ch 16

09-wt-aggregate-data.Rmd, 10-wt-longitudinal-analysis.Rmd
I moved a section of the ch 10 conclusion to the introduction of ch 9. I also added a paragraph to the introduction of ch 9 that explains why we have two chapters on agg data. Addresses #354
=> Coordinate introduction of aggregate data

07-wt-ed-ds-pipeline.Rmd
narrative edits and some minor code edits - mostly spacing out a large piped code chunk into multiple code chunks
=> chapter 7 edits

05-foundational-skills_1.Rmd, 06-foundational-skills_2.Rmd
=> re-merge content + URL fix

07-wt-ed-ds-pipeline.Rmd
This addreses the issue @nkenner raised with using percentage of points earned, instead of final grade. I've made changes to the code and text and tested that the chapter re-renders correctly.
=> C7 edits to replace percentage earned with final grade

02-how-to-use.Rmd, 06-foundational-skills_2.Rmd
change addy from authors@datascienceineducation.com to datascienceineducation@gmail.com
=> replace email address

05-foundational-skills_1.Rmd, 06-foundational-skills_2.Rmd
Ch.5 narrative edits. Also fixed headings in Ch.6 to remove Level 4+ headings.
=> Ch 5 Narrative + Ch 6 Headings

06-foundational-skills_2.Rmd
Also added spacing between separate lines of code w/in same code chunk, for readability
=> Narrative & clarifying edits for chapter 6

05-foundational-skills_1.Rmd, 06-foundational-skills_2.Rmd
=> Add requirements for {dataedu}

11-wt-text-analysis.Rmd
=> Move installation of tidytext to the top

07-wt-ed-ds-pipeline.Rmd
added explanations regarding warnings
=> added in explanatory notes regarding two error messages.

12-wt-social-network-analysis.Rmd
changed `as_tibble()` to `enframe(name = NULL)`
=> changed `as_tibble()` to `enframe(name = NULL)`

12-wt-social-network-analysis.Rmd
added explanation on creating a Twitter account
=> added explanation on creating a Twitter account

08-wt-gradebook.Rmd
added information on downloading the gradebook data
=> added information on downloading the gradebook data

07-wt-ed-ds-pipeline.Rmd, 08-wt-gradebook.Rmd, 09-wt-aggregate-data.Rmd, 12-wt-social-network-analysis.Rmd, 13-wt-multilevel-models.Rmd
=> Tagging issues

10-wt-longitudinal-analysis.Rmd
=> Quote Year

10-wt-longitudinal-analysis.Rmd
=> Fix download

15-data-science-in-your-job.Rmd, 16-teaching-data-science.Rmd
Removes numbers in chapter 16 headers and fixes a typo in chapter 15. This closes #514.
=> C16 headers

01-introduction.Rmd, 14-wt-machine-learning.Rmd
This PR addresses three fixes @ivelasq has made (or is in the process of making) in the documents we will submit:
- fixing parentheses (c1)
- changing building to build (c1)
- setting a chunk with `glimpse()` to `eval = FALSE`) (c14)
=> Minor copyedits before submitting

index.Rmd
add path to image, update citation, and add links to purchase book
still need to add image for book cover
=> update the welcome page

index.Rmd
minor edit to citation and to the purchasing the book section
=> minor edits to citation

05-foundational-skills_1.Rmd
added changes based on copyeditor feedback
=> added copyedit changes to chapter 5

07-wt-ed-ds-pipeline.Rmd
chapter 07 copyedits integrated
=> integrated all copyedits

10-wt-longitudinal-analysis.Rmd
This PR includes corrections to ch 10 described in #525
=> Ch10 edits

12-wt-social-network-analysis.Rmd
=> Fix for issue 525

01-introduction.Rmd
These are general edits to make the writing clearer and consistent with the rest of the book. I didn't make any changes to the general narrative. I did shorten sentences and removed unnecessary words where I could. I'll merge this without further review, but we can always open again if we need to revise.
=> Make edits for consistent style

10-wt-longitudinal-analysis.Rmd
Includes general review plus review for style. 
I tested the code and it runs. Still needs a code review for style and a grammar review.
=> Ch 10/write new content

08-wt-gradebook.Rmd
These are my edits for the gradebook walkthrough. @ivelasq I ran the code, which works. But they still need a review for style. Feel free to do that after these two commits are merged.
=> Ch 08/revisions

07-wt-ed-ds-pipeline.Rmd
Also add a section in import data to set up upcoming walkthroughs.
=> Resequence methods, data sources, load packages, and import

07-wt-ed-ds-pipeline.Rmd, 08-wt-gradebook.Rmd, 09-wt-aggregate-data.Rmd, 10-wt-longitudinal-analysis.Rmd
Added a section to each of the import headings in chapters 7-10 to make these more consistent. Still need to add the same section in chapters 11-14.
=> Refine imports
